### ISSUE TITLE
parallel_progbar got stuck when running large amount of operations

### ISSUE THREAD

**Issue by morriswong** [scnerd/miniutils#15]
I was trying to use the parallel_progbar for a parallel task:

```
with ThreadPool(16) as pool:
    results = parallel_progbar(main, zip(repeat(func), some_list), starmap=True)
```
It worked fine when the length of some_list is around 100, but when the list is getting larger, the parallel_progbar would stop at 99%, with a few iterations left undone and got stuck.

When I revert to the normal pool.starmap(), the code works as normal regardless of the list size.

Is there a way to fix that?

**Comment by scnerd** [comment]
`parallel_progbar` does work for longer-length lists; some of the stress-tests include `parallel_progbar` on lists of 100,000 items. Could you provide a complete example so I can replicate this error?

**Comment by scnerd** [comment]
@morriswong I'm going to close this issue since I cannot duplicate the error. Please re-open it if you can provide an example that doesn't work as it ought.
